[2024-01-16T06:59:51.641+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: STT-files.STT manual__2024-01-16T06:59:49.715215+00:00 [queued]>
[2024-01-16T06:59:51.656+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: STT-files.STT manual__2024-01-16T06:59:49.715215+00:00 [queued]>
[2024-01-16T06:59:51.657+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-16T06:59:51.678+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): STT> on 2024-01-16 06:59:49.715215+00:00
[2024-01-16T06:59:51.687+0000] {standard_task_runner.py:57} INFO - Started process 403 to run task
[2024-01-16T06:59:51.691+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'STT-files', 'STT', 'manual__2024-01-16T06:59:49.715215+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpmyahm_dl']
[2024-01-16T06:59:51.696+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask STT
[2024-01-16T06:59:51.771+0000] {task_command.py:416} INFO - Running <TaskInstance: STT-files.STT manual__2024-01-16T06:59:49.715215+00:00 [running]> on host 00276c0ab732
[2024-01-16T06:59:51.875+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='STT-files' AIRFLOW_CTX_TASK_ID='STT' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T06:59:49.715215+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-16T06:59:49.715215+00:00'
[2024-01-16T06:59:51.879+0000] {logging_mixin.py:154} INFO - b'{"language": "ko-KR", "completion": "sync", "callback": null, "userdata": null, "wordAlignment": true, "fullText": true, "forbiddens": null, "boostings": null, "diarization": null}'
[2024-01-16T06:59:59.848+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task.py", line 24, in STT
    data = json.loads(clova_output)
NameError: name 'json' is not defined
[2024-01-16T06:59:59.861+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=STT-files, task_id=STT, execution_date=20240116T065949, start_date=20240116T065951, end_date=20240116T065959
[2024-01-16T06:59:59.877+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task STT (name 'json' is not defined; 403)
[2024-01-16T06:59:59.904+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-16T06:59:59.921+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
